
- name: Ensure kernel module 'freevxfs' is disabled
  lineinfile:
    create: yes
    dest: "/etc/modprobe.d/{{item}}.conf"
    regexp: '{{item}}'
    line: "install {{item}} /bin/true"
  with_items:
    - freevxfs
    - udf
    - squashfs
    - hfsplus
    - jffs2
    - hfs
    - cramfs
  tags:
    - kernel_module_udf_disabled
    - kernel_module_freevxfs_disabled
    - kernel_module_squashfs_disabled
    - kernel_module_hfsplus_disabled
    - kernel_module_jffs2_disabled
    - kernel_module_hfs_disabled
    - kernel_module_cramfs_disabled
    - low_severity
    - disable_strategy
    - low_complexity
    - medium_disruption
    - CCE-80138-1
    - NIST-800-53-CM-7
    - NIST-800-171-3.4.6
